# CONFIG DEPLOYMENT
apiVersion: apps/v1
kind: Deployment
metadata:
  name: config-server
  labels:
    app: config-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: config-server
  template:
    metadata:
      labels:
        app: config-server
    spec:
      containers:
        - name: config-server
          image: epicmarket/config-server
          ports:
            - containerPort: 8811
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: kubernetes, native

---

# CONFIG SERVICE

apiVersion: v1
kind: Service
metadata:
  name: config-server-service
spec:
  ports:
    - protocol: TCP
      port: 8811
      targetPort: 8811
  selector:
    app: config-server
  type: ClusterIP

---

# API DEPLOYMENT

apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-compositor
  labels:
    app: api-compositor
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-compositor
  template:
    metadata:
      labels:
        app: api-compositor
    spec:
      containers:
        - image: epicmarket/api-compositor
          name: api-compositor
          ports:
            - protocol: TCP
              containerPort: 8080
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: kubernetes
            - name: logging.level.root
              value: DEBUG

---

# API SERVICE

apiVersion: v1
kind: Service
metadata:
  name: api-compositor-service
spec:
  ports:
    - port: 8005
      targetPort: 8080
  selector:
    app: api-compositor
  type: LoadBalancer

---

# CRUD DEPLOYMENT
apiVersion: apps/v1
kind: Deployment
metadata:
  name: crud-service
  labels:
    app: crud-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: crud-service
  template:
    metadata:
      labels:
        app: crud-service
    spec:
      containers:
        - name: crud-service
          image: epicmarket/crud-service
          ports:
            - protocol: TCP
              containerPort: 8080
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: kubernetes
            - name: logging.level.root
              value: DEBUG

---

# CRUD SERVICE

apiVersion: v1
kind: Service
metadata:
  name: crud-service
spec:
  ports:
      - port: 8003
        targetPort: 8080
  selector:
    app: crud-service
  type: ClusterIP
