apiVersion: skaffold/v2beta28
kind: Config
metadata:
  name: epic-market
build:
  artifacts:
    - image: epicmarket/config-server
      context: ./config-server
      docker: { }
    - image: epicmarket/api-compositor
      context: ./api-compositor
      docker: { }
    - image: epicmarket/buyer-api
      context: ./buyer-api
      docker: { }
    - image: epicmarket/seller-api
      context: ./seller-api
      docker: { }
    - image: epicmarket/payment-api
      context: ./payment-api
      docker: { }
    - image: epicmarket/logistic-api
      context: ./logistic-api
      docker: { }
    - image: epicmarket/file-storage
      context: ./file-storage
      docker: { }
  local:
    push: true
  tagPolicy:
    dateTime: {}

deploy:
  kubectl:
    manifests:
      # Kafka for minikube
      - deployment/kafka/wurstmeister/zookeeper-deployment.yml
      - deployment/kafka/wurstmeister/zookeeper-service.yml
      - deployment/kafka/wurstmeister/kafka-deployment.yml
      - deployment/kafka/wurstmeister/kafka-service.yml
      # Core services
      - config-server/config-server-deployment.yml
      - api-compositor/api-compositor-deployment.yml
      - buyer-api/buyer-api-deployment.yml
      - seller-api/seller-api-deployment.yml
      - payment-api/payment-api-deployment.yml
      - logistic-api/logistic-api-deployment.yml
      # File storage set
      - file-storage/deployment/postgres-storage.yml
      - file-storage/deployment/postgres-deployment.yml
      - file-storage/deployment/file-service.yml
