FROM openjdk:17.0.1

VOLUME /tmp

COPY build/libs/logistic-api.jar app.jar

ENV JAVA_OPTS="-Xmx128m -Xms64m"
ENV SERVICE_NAME="logistic-api"
LABEL APP=${SERVICE_NAME}
LABEL DOMAIN="epic-market"

ENTRYPOINT [ "sh", "-c", "java $JAVA_OPTS -Djava.security.egd=file:/dev/./urandom -jar /app.jar"]
