FROM openjdk:16.0.2-jdk-slim

VOLUME /tmp

COPY build/libs/config-server.jar app.jar

ENV JAVA_OPTS="-Xmx128m -Xms64m"
ENV SERVICE_NAME="config-server"
LABEL APP=${SERVICE_NAME}
LABEL DOMAIN="epic-market"

ENTRYPOINT [ "sh", "-c", "java $JAVA_OPTS -Djava.security.egd=file:/dev/./urandom -jar /app.jar"]
