
# API DEPLOYMENT

apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-compositor
  labels:
    app: api-compositor
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-compositor
  template:
    metadata:
      labels:
        app: api-compositor
    spec:
      containers:
        - image: epicmarket/api-compositor
          name: api-compositor
          ports:
            - protocol: TCP
              containerPort: 8080
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: kubernetes
            - name: logging.level.root
              value: DEBUG

---

# API SERVICE

apiVersion: v1
kind: Service
metadata:
  name: api-compositor-service
spec:
  ports:
    - port: 8005
      targetPort: 8080
  selector:
    app: api-compositor
  type: LoadBalancer
