

# PAYMENT DEPLOYMENT
apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-api
  labels:
    app: payment-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payment-api
  template:
    metadata:
      labels:
        app: payment-api
    spec:
      containers:
        - name: payment-api
          image: epicmarket/payment-api
          ports:
            - protocol: TCP
              containerPort: 8080
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: kubernetes
            - name: logging.level.root
              value: DEBUG

---

# PAYMENT SERVICE

apiVersion: v1
kind: Service
metadata:
  name: payment-api
spec:
  ports:
    - port: 8003
      targetPort: 8080
  selector:
    app: payment-api
  type: ClusterIP
