apiVersion: v1
data:
  ca.crt: |
    -----BEGIN CERTIFICATE-----
    MIIELTCCApWgAwIBAgIRANtF3f50QOQmYJ01Rk3xezMwDQYJKoZIhvcNAQELBQAw
    LzEtMCsGA1UEAxMkZjc2ZDIxYjYtMWM2Yy00MmM3LWE5ZWQtOTkwODczMmZlNWM0
    MCAXDTIxMDkxMDA3MTMwMVoYDzIwNTEwOTAzMDgxMzAxWjAvMS0wKwYDVQQDEyRm
    NzZkMjFiNi0xYzZjLTQyYzctYTllZC05OTA4NzMyZmU1YzQwggGiMA0GCSqGSIb3
    DQEBAQUAA4IBjwAwggGKAoIBgQCfWTUBrmGHRYjYCA4ZW9XbYp23lLZ0U369D2n9
    0XY9FVgfRYW+Akd51UWMI0hJeHDcqZtp6n+fdHGT1eAJz/SfnYJN+v9cbZt32lB2
    +rAtOacZqbpK5J5vNnABNzwV0EkNhx6otaKpEVtRQsjRIEOVdYKjX2M/Iv607eMc
    YSKtjwazvY0xgn7u2Fl98h90NDL+tFxDmfnTWAm5CVKl1gBTo6JKgpVSrATTQbTy
    6RzOwZeiHrVrCoTaA6TzNPn55nm0RN3wrexT20O2QuXQkXIgvImqq5lI3Hzk9mgn
    89X2JyIOFQWzN/QTY0su+7zRz4jozt1mcQnL47yDzxWSYzAW36xhBdbM0mQH/Bek
    tOMdehTFCchF+hUALNdh0p/S0LkHDxnV7/6cgOJZdj55Uv+TTLALXHuB7pQE9YUk
    /CHIWGUCh+YtRh/7QAl0oVT/uaIX7vtCeeUeI25s/nMDaHZQ2c7U1k6OhO8j+tYN
    dZgaSavowyMjwZTQ78dBD6lXjCcCAwEAAaNCMEAwDgYDVR0PAQH/BAQDAgIEMA8G
    A1UdEwEB/wQFMAMBAf8wHQYDVR0OBBYEFOTi13xZcWMyFuckdl2Jm8hzm1sPMA0G
    CSqGSIb3DQEBCwUAA4IBgQAo/qqlTL/ySK/fKDPFAXPE5R1DMYu/avrWJCT0rzZp
    hwvsN0ffFPRAYidHNDF9qxqsa/Qb+xEYMjCjsHXhHGQlziTqfwAxGP/RAFClGAN0
    IcMldfF99QZX4sb41cwP5mUqRTZ7JnlFnCiQDdUS2nUFvZpYZPAZFXyPXypQquJG
    Q3uiGjkClofwcgsfbDCnxdxSfX2/5Uyde1tjLJ7Yh8DIlCSQme8F5BmcGMf/WJj/
    v3F97XEWOCdxhQy2SCALaaT+XiKNZq0SkmGPaJXCb7gHTwIWhW/30cHYGuh8dVrW
    cDFgPYTEBv9uLnoJOnyLmccbynlaiK+SZYJkA3I0CcWVKCC2IYyHIzglKr63Cgc6
    E9vW9DvXQbLhCRPwUGu5DrpZTisfSXV2aOuIp/EQtReUeT5avDej/h+e/khqLnG3
    ZLDqiT1QbzxofTFwwP5SWdqfcQ1QVxUXMl02zJ+ruEqORzv4WeASRP9BXF1Xmtit
    WQ4JA8qyZ8AzH1Z9xnDuYR8=
    -----END CERTIFICATE-----
kind: ConfigMap
metadata:
  creationTimestamp: "2021-09-10T08:15:20Z"
  name: kube-root-ca.crt
  namespace: default
  resourceVersion: "310"
  uid: 7bed99f3-e9a4-4aee-966b-05addfcf11e1
